version: '3.8'

services:
  node-app:
    build: .
    command: npm run start:dev
    image: node-app
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node-network

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
